### ISSUE TITLE
Use chrono?

### ISSUE THREAD

**Issue by thejpster** [eldruin/mcp794xx-rs#1]
It might be useful if `get_timestamp()` returned a `chrono::NaiveDateTime`. We'd then have access to all the useful chrono methods for formatting, converting to POSIX time, etc.

**Comment by eldruin** [comment]
Sorry I somehow missed this issue. `chrono::NaiveDateTime` seems like a good fit.
I will do a new release in the next days and let you know here.

**Comment by eldruin** [comment]
I changed this in version 0.2.0. Please let me know if it works well.
Here the extract from the CHANGELOG:
> #### [0.2.0] - 2020-02-09
> ##### Changed
> - Changed `get_datetime()` and `set_datetime()` parameter from `DateTime`
>   to `chrono::NaiveDateTime`.
> ##### Added
> - Methods to set and get date and time using `chrono::NaiveDate` and `chrono::NaiveTime`:
>     - `get_time()`
>     - `set_time()`
>     - `get_date()`
>     - `set_date()`
> - `chrono` dependency.
> ##### Removed
> - `DateTime` data structure was replaced by `chrono::NaiveDateTime`.
>

**Comment by eldruin** [comment]
Closing. Anyway feel free to comment or reopen.
